### ISSUE TITLE
osx.md Step 1 docker-compose.yml filename problem

### ISSUE THREAD

**Issue by t4k** [esmero/archipelago-deployment#1]
> ~/Development/archipelago-deployment $ docker-compose up -d
> ERROR: 
>         Can't find a suitable configuration file in this directory or any
>         parent. Are you in the right directory?
> 
>         Supported filenames: docker-compose.yml, docker-compose.yaml

I renamed the file (`mv docker-compose-nginx.yml docker-compose.yml`) and everything continues as expected.

**Comment by DiegoPino** [comment]
@t4k totally. My mistake when pushing this branch. We have that file in the .gitignore statement to avoid people committing that file when making pull requests if they made local changes. I just forced a copy here but will also update documentation accordingly. Thanks for keeping an eye. Please let me know if you find more issues.

**Comment by DiegoPino** [comment]
@t4k i also updated docs accordingly. I think i should not even ship the docker-compose.yml file now that docs are there, will see how things go and decide on that.

**Comment by t4k** [comment]
I think the `cp` step is a fair one. It is how a number of other projects provide default configuration that allows for local modification (Drupal VM comes to mind).
