### ISSUE TITLE
Update Xdebug for RC3

### ISSUE THREAD

**Issue by DiegoPino** [esmero/archipelago-deployment#114]
# What?

Yep, xdebug version 3 (I still love error_log but Ok, this sounds reasonable!)

- Update Container (done!) to match PHP 7.4.20
- Update docker-compose.dev.yml for XDEBUG 3
- Add a custom php.ini 
- Add instructions to archipelago-documentation (simpler now)

**Comment by DiegoPino** [comment]
@aksm is this also true for RC3D9? Please give me your thumbs if so

**Comment by aksm** [comment]
@DiegoPino Whoops, no. Will work on that now.

**Comment by DiegoPino** [comment]
Solved by super duper @aksm  via https://github.com/esmero/archipelago-deployment/commit/b4b28dbada4412d1c925687856a1427b2dd50f74

Thanks!
