### ISSUE TITLE
Document D8 to D9 manual Upgrade for this repository

### ISSUE THREAD

**Issue by DiegoPino** [esmero/archipelago-deployment#127]
# What?

Similar (very) to https://github.com/esmero/archipelago-deployment-live/blob/1.0.0-RC3/docs/upgradeFromD8ToD9.md
but with a few changes

**Comment by aksm** [comment]
@DiegoPino Sorry for the delay. Working on this now. I've copied the file over and will go step by step and adjust.

**Comment by DiegoPino** [comment]
Thanks @aksm

**Comment by DiegoPino** [comment]
Please adjust via a Pull request. No direct edit so we can review! Thanks!

**Comment by DiegoPino** [comment]
Solved via https://github.com/esmero/archipelago-deployment/commit/c93febc70f8701609d98aac33054367196d20ecc (and a few other more!)
