### ISSUE TITLE
"demo" and "jsonapi" users can not be created at the same time in Terminal

### ISSUE THREAD

**Issue by mitchellkeaney** [esmero/archipelago-deployment#13]
In the OSX deployment documentation, Step 4 provides two scripts for creating users "demo" and "jsonapi":
```
docker exec -ti esmero-php bash -c 'drush ucrt demo --password="demo"; drush urol metadata_pro "demo"'
docker exec -ti esmero-php bash -c 'drush ucrt jsonapi --password="jsonapi"; drush urol metadata_pro "jsonapi"'
```
I made the mistake of running both lines at the same time, which Terminal cannot complete and was only able to create "demo". I found that the user must copy each script separately and run individually in order for both the "demo" and "jsonapi" users to be created successfully.

**Comment by DiegoPino** [comment]
@mitchellkeaney totally true. Those commands can lead to that problem if both lines are copined into the terminal at the same time. I will also fail silently, Thanks for reporting 😃 . I will make a pull request to fix that and will let you know here (and in the pull) once that is done

**Comment by DiegoPino** [comment]
Solved via https://github.com/esmero/archipelago-deployment/commit/21e00f443b6d1c2479e19be6d95c1ada63c698c5
