### ISSUE TITLE
Change frictionlessdata/datapackage version to dev-main in composer.json

### ISSUE THREAD

**Issue by patdunlavey** [esmero/archipelago-deployment#130]
# What?

Composer require frictionlessdata/datapackage dev-master results in an error. The branch name has changed to "main". Therefore [composer.json](https://github.com/esmero/archipelago-deployment/blob/1.0.0-RC2/composer.json#L82) needs to replace `"frictionlessdata/datapackage": "dev-master",` with `"frictionlessdata/datapackage": "dev-main",`

**Comment by DiegoPino** [comment]
@patdunlavey all has been updated on this repository except RC1 which is something I won't retroactively maintain. Please test and let me know if you find any more issues. strawberryfield/strawberryfield has been retroactively updated too on RC1, RC2 and also now on RC3.

**Comment by patdunlavey** [comment]
Thank you so much Diego. You are awesome! I'll test in the morning.

**Comment by patdunlavey** [comment]
Tested and it works great!
