### ISSUE TITLE
Some demo objects fail on processing AMI set

### ISSUE THREAD

**Issue by aksm** [esmero/archipelago-deployment#135]
# What?
Some of the demo objects fail on ingest (see screenshot below).

![screenshot-localhost_8001-2021 09 01-13_48_36](https://user-images.githubusercontent.com/15711380/131719329-c28c192c-0b33-4dac-a008-cd95406158a8.png)

# Why?

Example: `https://archipelago.nyc/do/130/iiif/45ae14db-b784-46bf-a610-f41ade59d48d/full/full/0/hs-2015-02-a-hires_jpg.jpg` is maybe a typo of `https://archipelago.nyc/do/130/iiif/45ae14db-b784-46bf-a610-f41ade59d48d/full/full/0/hs-2015-02-a-hires.jpg`.

The other links seem fine so I'm not sure why those are failing. Will see if I can find some relevant logs.

**Comment by DiegoPino** [comment]
@aksm any chance you had an Internet Glitch while ingesting? All those are remote URLs that may have failed to connect to during the process. Deleting them and trying again may solve the issue. @alliomeria can you check / double check those links?

**Comment by aksm** [comment]
@DiegoPino Hmm, I don't think so. I tried the ingest with another deployment of a different branch and also tried deleting the objects and re-ingesting and had the same with the same objects, but maybe a local machine or network issue?

**Comment by DiegoPino** [comment]
Yes, I wonder if that is the issue?

From that same local machine, can you try "curl" any of those URLs?

e.g https://archipelago.nyc/do/51/iiif/6b1da3cf-d91a-4dd4-98d7-5dc0cdb85d67/full/full/0/default.m4v (if that is the same URL that is failing).

To test correctly you may need to do it from the host machine (your linux) and then from your docker container (by logging into the esmero-php container)

Let me know how that goes

**Comment by aksm** [comment]
Curl on both host machine and docker container is successful.

**Comment by DiegoPino** [comment]
Ok, any chance you skipped changing the permissions for private folder in the instructions or had to amend (repeat a command)? That error may happen if
1.- the URL is not accesible
2.- We can not persist the file
3.- We have no permissions to write the file.

Also, this is all on RC2 right? no AMI 0.2.0 but 0.1.0?

**Comment by aksm** [comment]
Sorry! Seems like user error / local resource issue. Will close for now and look into my dev environment.

**Comment by DiegoPino** [comment]
@aksm all good! Thanks!
