### ISSUE TITLE
Re-allow JSON API early rendering Module for Drupal 9

### ISSUE THREAD

**Issue by DiegoPino** [esmero/archipelago-deployment#136]
# What?

We had removed this module because it was not supported on D9. We use it because the JSON:API permeate some caching issues that trigger when we ingest via Drush. Not the case anymore

https://www.drupal.org/project/jsonapi_earlyrendering_workaround

So, we should for 1.0.0 re-add to our stack!

**Comment by aksm** [comment]
Fixed by Diego via e67aa9d2ccb5da6c4467753cb8ac293de069448a.
