### ISSUE TITLE
Update configs for Data CreativeWorks Series Drupal view

### ISSUE THREAD

**Issue by aksm** [esmero/archipelago-deployment#162]
# What?
It was discovered recently on a team call that a block had snuck into the Data CreativeWorks Series view and that the sort criteria needed to be adjusted to use the sequence_id.

**Comment by alliomeria** [comment]
Hello @aksm & @DiegoPino --following up on discussions we had earlier this week. 

Noting here the related updates needed:
- for the Creative Work Series Children View Sort Criteria, adding the sequence_id and removing the Changed (Exposed) 
- for the Digital Object and Digital Object Collection Display modes for "Digital Object with Thumbnail for Grid", disabling Last Modified

Thank you! 🙏 😀

**Comment by DiegoPino** [comment]
@aksm can you include in another pull  "Digital Object and Digital Object Collection Display modes for "Digital Object with Thumbnail for Grid", disabling Last Modified" work too? I will keep this issue open

**Comment by aksm** [comment]
> Hello @aksm & @DiegoPino --following up on discussions we had earlier this week.
> 
> Noting here the related updates needed:
> 
> * for the Creative Work Series Children View Sort Criteria, adding the sequence_id and removing the Changed (Exposed)
> * for the Digital Object and Digital Object Collection Display modes for "Digital Object with Thumbnail for Grid", disabling Last Modified
> 
> Thank you! pray grinning

@alliomeria Should the sequence_id sort be exposed for this?

**Comment by DiegoPino** [comment]
We should start without exposing it for now... future work might need this but only makes sense if a form is going to be added to the block and positioned to be able to search. If you want to do that whole work the++ but urgent is the proper sorting for now (ascending)
