### ISSUE TITLE
FYI, FWIW; install broken b/c https://schema.org/docs/jsonldcontext.json give a 503

### ISSUE THREAD

**Issue by tingletech** [esmero/archipelago-deployment#17]
Hi,

I was trying to follow the directions @ https://github.com/esmero/archipelago-deployment/blob/8.x-1.0-beta1/docs/osx.md#step-1-docker-deployment

I get 

```
In RequestException.php line 113:
                                                                                                                    
  Server error: `GET https://schema.org/docs/jsonldcontext.json` resulted in a `503 Service Unavailable` response:  
                                                                                                                    
  <html><head>                                                                                                      
  <meta http-equiv="content-type" content="text/html;charset=utf-8">                                                
  <title>503 Over Quota</title>                                                                                     
  <style><! (truncated...)                                                                                          
```

when I run 

```
archipelago-deployment % docker exec -ti -u www-data esmero-php bash -c "cd web;../vendor/bin/drush -y si --verbose config_installer  config_installer_sync_configure_form.sync_directory=/var/www/html/config/sync/ --db-url=mysql://root:esmerodb@esmero-db/drupal8 --account-name=admin --account-pass=archipelago -r=/var/www/html/web --sites-subdir=default --notify=false install_configure_form.enable_update_status_module=NULL install_configure_form.enable_update_status_emails=NULL;drush cr;chown -R www-data:www-data sites;"
```

**Comment by DiegoPino** [comment]
HI Brian,

How unfortunate. Schema.org <http://schema.org/> run out  of its quota! I thought that would never happen. Let me think/code about some options there.
Briefly: Schema.org <http://schema.org/> Schema is used to give people a set of initial Exposed Metadata properties for Indexing, it downloads once only, basically just some options but that 503 error is not correctly handled by the code.
Its really not part of the code itself, but part of the deployment configuration. I can change the configs to they download that file from another source or even local, but i don’t want to confuse you with moving pieces during your first interaction with it.

I will open an ISSUE and have a  fix by tomorrow. Will follow up there to give you some pointers on how to update your local deployment (its a single call to a script).

You can also try later today or tomorrow. Schema.org <http://schema.org/> being down will affect a LOT of people so i guess they will react on time or faster than me. And i’m happy we are the first ones to deal with this! But still shameful!

Thanks, stay tuned!!



Diego Pino Navarro
Metropolitan New York Library Council
599 11th Av. New York, NY 10036

**Comment by DiegoPino** [comment]
@tingletech some updates.
Google decided to pay the bill (for its own service 👀 ) so [schema.org](https://schema.org) is back and you can executing that step again. All should go smoothly now 🎉 

But, i also did some code to alleviate partially the fact that `WebSem` totally depends on external, public services, e.g JSON-LD uses `@context` resolving from URLS and that is, as now, a red flag and larger global issue really. 

See:
https://github.com/esmero/strawberryfield/issues/51
And a corresponding pull:
https://github.com/esmero/strawberryfield/pull/52

Not needed in your case (yet) but good to have for our next beta.

Thanks for reporting this and sorry you had to go through this. We all learned, there is nothing we can take for granted in the web.

**Comment by DiegoPino** [comment]
Closing this since we fixed it. Hope @tingletech had the chance (and the energy) to give this another try. Here to help if you ever want to try again 😄
