### ISSUE TITLE
PHP 8 docker container updates

### ISSUE THREAD

**Issue by aksm** [esmero/archipelago-deployment#195]
# What?
The PHP intl extension (for citeproc-php support) has been added to docker images so docker-compose files need to pull those. Additionally, the dev container needs xdebug config updates and a new filename convention (see esmero/archipelago-docker-images#46) so they can be overridden by users as needed.

**Comment by DiegoPino** [comment]
Resolved via https://github.com/esmero/archipelago-deployment/commit/5b666a8aa22cb55dd7cd4559664446e032bdea96
