### ISSUE TITLE
Create docker-compose.dev.yml file

### ISSUE THREAD

**Issue by marlo-longley** [esmero/archipelago-deployment#20]
### Why.

Well, I am referencing `docker-compose.dev.yml` [here](https://github.com/esmero/archipelago-documentation/pull/23). It helps to launch the development php image and is used as an override file in `docker-compose up` during development or debugging sessions. So I need to add it to the repo for testing and approval.

I am open to a different approach but for now, wish for you @DiegoPino to have access to the file.

**Comment by DiegoPino** [comment]
Solved via https://github.com/esmero/archipelago-deployment/commit/87fb3921f91d728e32ef6cd2a7f42655e6550f0b
