### ISSUE TITLE
Prepare for Twig 3 in Drupal 10

### ISSUE THREAD

**Issue by aksm** [esmero/archipelago-deployment#214]
# What?
Drupal 10 is on [Twig 3](https://www.drupal.org/node/3256890) so we should make sure we don't have any changes we need to account for in the templates we ship.

**Comment by DiegoPino** [comment]
Resolved on 1.3.0 and 1.2.0 via a bunch of commits at code level and also defaults shipped
https://github.com/esmero/format_strawberryfield/commit/cf1b37834d3d79c37d4d9712f12b38970e8fa859
