### ISSUE TITLE
MariaDB 10.5.10 Exception

### ISSUE THREAD

**Issue by aksm** [esmero/archipelago-deployment#216]
# What?
Running `drush updatedb` threw the following error on RC3 with MariaDB 10.5.10:

> [notice] Update started: ami_update_8905
> [error] Exception thrown while performing a schema update. SQLSTATE[42S22]: Column not found: 1054 Unknown column ‘“drupal”.“base_table”.“set”’ in ‘CHECK’: ALTER TABLE “ami_setentity” ADD `report_file__target_id` INT unsigned NULL DEFAULT NULL COMMENT ‘The ID of the file entity.’; Array
> (
> )
> 
> [error] Update failed: ami_update_8905

Here's a reference issue: shopware/platform#1861

This is a problem with this specific MariaDB version so updating to a later version docker image resolves the issue.

**Comment by DiegoPino** [comment]
Not an issue since 1.1.0
