### ISSUE TITLE
drupal/facets:2.0.5 has JS errors

### ISSUE THREAD

**Issue by DiegoPino** [esmero/archipelago-deployment#224]
See https://github.com/esmero/archipelago-deployment-live/issues/93

This needs to be tested and patches soon. Should be for 1.0.0 and 1.1.0 (except if your composer.lock is already fetching 2.0.5)

**Comment by aksm** [comment]
Closing because this has been fixed for 2.0.5 stable since this issue was opened:

https://git.drupalcode.org/project/facets/-/blob/2.0.5/modules/facets_range_widget/js/slider.js#L6
