### ISSUE TITLE
Update metadata display entity file names in d8content

### ISSUE THREAD

**Issue by aksm** [esmero/archipelago-deployment#234]
# What?
Now that we're using UUIDs in the filenames for the `scripts/archipelago/import_export.sh` script, we should update the filenames for the existing entities in `d8content/` we use for deployment. This will require updating the `scripts/archipelago/deploy.sh` and `scripts/archipelago/update_deployed.sh` scripts since the current filenames are hard-coded there.

**Comment by DiegoPino** [comment]
This won't be made. Humans can not read UUIDs on files.
