### ISSUE TITLE
Alpine 3.18 DNS over TCP support

### ISSUE THREAD

**Issue by aksm** [esmero/archipelago-deployment#245]
# What?
See [here](https://www.theregister.com/2023/05/16/alpine_linux_318/) for reference. The base Alpine Linux image used by many projects (including ours) apparently did not support DNS over TCP, but 3.18 now does. It's possible that this will resolve the occasional mysterious DNS issues we've come across.

**Comment by DiegoPino** [comment]
Not sure this is need right now, not sure why DNS of UDP was a problem? Also next release is on PHP 8.3. So I will have to build all containers again. Closing for now
