### ISSUE TITLE
Rebuild view modes for Display Suite module

### ISSUE THREAD

**Issue by aksm** [esmero/archipelago-deployment#249]
# What?
See a866bf1. Per @DiegoPino, 5.0.x-dev is incompatible with our settings in view modes. Will come back and update this issue with more details.

**Comment by DiegoPino** [comment]
Al. Before going this route (the complete rewrite) we should test 1 or two. Make sure display mode changes via our type mappings and also that things actually render! Thanks!

**Comment by DiegoPino** [comment]
No change needed here since 1.3.0
