### ISSUE TITLE
RuntimeException: Adding non-existent permissions to a role is not allowed. The incorrect permissions are "search content". in Drupal\user\Entity\Role->calculateDependencies() (line 207 of /var/www/html/web/core/modules/user/src/Entity/Role.php).

### ISSUE THREAD

**Issue by fishfree** [esmero/archipelago-deployment#256]
I created a new role, and arbitrarily grant any permissions to it, when click Save permissions button, it would show errors as in the title.
The latest 1.3.0 version.
FYI: https://www.drupal.org/project/varbase_search/issues/3343821

**Comment by DiegoPino** [comment]
@fishfree good catch. Some Drupal 9 roles are deprecated in 10 and I missed those. You can (if in a rush) export/import the "roles" again via the /admin/config/development/configuration/full/export (and import) or use drush cim (targeting just the role files)


I just pushed into 1.3.0 New Roles YML files (those should work for you)

**Comment by fishfree** [comment]
@DiegoPino Thank you very much!
