### ISSUE TITLE
Fix IIIF CWS Series and the Children template

### ISSUE THREAD

**Issue by DiegoPino** [esmero/archipelago-deployment#257]
# What?

There is a long lasting typo in this template that kicks in when a Child Object has both images and Videos.
(http://localhost:8001/metadatadisplay/13)

- itemCount needs to initialized to 0 outside of any loop
- CantaloupeID is not correctly defined for Videos
- The Image id (thumbnail) says:  {{CantaloupeID}}1; and should be {{CantaloupeID}};1

@alliomeria ping.

**Comment by alliomeria** [comment]
@DiegoPino pong!

**Comment by DiegoPino** [comment]
Resolved via https://github.com/esmero/archipelago-deployment/commit/edcb255058d57b4b9020026271975abf944c1392
