### ISSUE TITLE
Advanced Search Default Configurations

### ISSUE THREAD

**Issue by alliomeria** [esmero/archipelago-deployment#259]
# What's needed? 

We need to provide configuration files for default Advanced Search:
- View for Advanced Search
- Facets
- Facet Summary
- Blocks for Facets & Facet Summary
- Custom block for advanced search page
- Updated Navigation Menu

## Related/relies on:
- https://github.com/esmero/format_strawberryfield/issues/400
- https://github.com/esmero/format_strawberryfield/pull/403
- https://github.com/esmero/format_strawberryfield/issues/404
- https://github.com/esmero/archipelago_subtheme/issues/42

**Comment by DiegoPino** [comment]
Resolved via by @alliomeria  https://github.com/esmero/archipelago-deployment/commit/40d4e85721e389f1f63d2a4be036a34aee21cb71

Includes also documentation at https://docs.archipelago.nyc/1.3.0/search_advanced/
