### ISSUE TITLE
Provide example Config/Views for new Metadata API endpoint

### ISSUE THREAD

**Issue by DiegoPino** [esmero/archipelago-deployment#268]
# What?

@alliomeria probably a DC based` OAI-PMH` one. Means also templates/Views/config. Documentation should be at least be a boiler plate with the basics?

**Comment by alliomeria** [comment]
Ok @DiegoPino

**Comment by alliomeria** [comment]
Working on this today @DiegoPino

**Comment by alliomeria** [comment]
Marking this resolved by https://github.com/esmero/archipelago-deployment/pull/271 😸
