### ISSUE TITLE
URL for installing Docker for Mac needs updating

### ISSUE THREAD

**Issue by johnnydtan** [esmero/archipelago-deployment#279]
In the section https://github.com/esmero/archipelago-deployment/blob/1.4.0/docs/osx.md#osx-macos, the URL for installing Docker for Mac is outdated.

Currently, it's: https://docs.docker.com/docker-for-mac/
It should be: https://docs.docker.com/desktop/install/mac-install/

**Comment by DiegoPino** [comment]
Resolved via https://github.com/esmero/archipelago-deployment/commit/691911d0a13d7e8a2ea4e0109d1f783b880d03f8 by @johnnydtan
