### ISSUE TITLE
Update Archipelago Subtheme settings to match new schema

### ISSUE THREAD

**Issue by marlo-longley** [esmero/archipelago-deployment#39]
## What is needed? 

Relating to https://github.com/esmero/archipelago_subtheme/pull/14 in the subtheme, we pushed an updated schema.
This means some of the old settings were of the wrong type to match the new schema.

## What to do?
Update /config/sync/archipelago_subtheme.settings to match new schema types.

**Comment by DiegoPino** [comment]
Do you have the YAML already? Let me know. If not i can push

**Comment by marlo-longley** [comment]
@DiegoPino the YAML was pushed in the subtheme repo. I am misunderstanding your question?

**Comment by marlo-longley** [comment]
@DiegoPino I will also push into the subtheme /config/settings, yes. Give me a couple minutes.
