### ISSUE TITLE
Identify not running on draft ADOs

### ISSUE THREAD

**Issue by patdunlavey** [esmero/archipelago-deployment#82]
See https://github.com/esmero/strawberryfield/issues/120

**Comment by patdunlavey** [comment]
Solution is to set defaults for 
```
identify_exec_path: /usr/bin/identify
pdfinfo_exec_path: /usr/bin/pdfinfo
```
in config/sync/strawberryfield.filepersister_service_settings.yml

Pat will issue PRs for 1.0.0-RC1 and 1.0.0-RC1D9

**Comment by patdunlavey** [comment]
Two pull requests created @DiegoPino :
- https://github.com/esmero/archipelago-deployment/pull/83
- https://github.com/esmero/archipelago-deployment/pull/84

**Comment by DiegoPino** [comment]
@patdunlavey both merged. Thanks! Closing this as solved via https://github.com/esmero/archipelago-deployment/commit/a4300866b450569c682bc0a36513c86c31a5994e and https://github.com/esmero/archipelago-deployment/commit/bacf1e706c9be54f20e077cb4762bc20f5d47d99

Celebration time 🥇 ,awesome
